-- sudo -u postgres createuser --interactive --pwprompt --echo
-- sudo -u postgres createdb homer

CREATE ROLE homer PASSWORD 'md554e8c10996t10cb0dee5c2e5070b2863' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE DATABASE "homer";
\c homer

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE TABLE "locations" (
  "id" int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(16) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "name" UNIQUE ("name")
);

CREATE TABLE "values" (
  "time" timestamptz NOT NULL,
  "location_id" int2 NOT NULL,
  "temp" float8,
  "humd" float8,
  "press" float8,
  PRIMARY KEY ("time", "location_id"),
  CONSTRAINT "location" FOREIGN KEY ("location_id") REFERENCES "locations"  ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX "location" ON "values" USING btree (
  "location_id"
);

SELECT create_hypertable('values', 'time');

INSERT INTO "locations" ("name") VALUES ('balcon');
INSERT INTO "locations" ("name") VALUES ('bedroom');
INSERT INTO "locations" ("name") VALUES ('street-n');
INSERT INTO "locations" ("name") VALUES ('led-hall');
INSERT INTO "locations" ("name") VALUES ('water-c');
INSERT INTO "locations" ("name") VALUES ('water-h');

